### ISSUE TITLE
Support gzip encoding

### ISSUE THREAD

**Issue by ctmay4** [deansg/jeocodio#19]
In the latest release of Geocodio, he added support for gzip encoding. I tested externally and it is working well. 

The library doesn't currently set the "Accept-Encoding: gzip" header so it works fine. However it seems there should be an option to do so.

Just playing around with it I got it to work. 

First, the header needs to be added to the request. Just one single line added to the request builders.

```java
    public CompletableFuture<GeocodingResponse> geocodeAsync(GeocodingRequest request) {
        var query = initializeRequestQuery();
        query.put("q", request.q());
        query.put("country", request.country());
        query.put("fields", formatFieldsParam(request.fields()));
        query.put("limit", Optional.ofNullable(request.limit()).map(Object::toString).orElse(null));
        query.put("format", request.format());
        query.put("street", request.street());
        query.put("city", request.city());
        query.put("state", request.state());
        query.put("postal_code", request.postalCode());
        var uri = buildURI("geocode", query);
        var httpRequest = HttpRequest.newBuilder()
                .header("Accept-Encoding", "gzip")
                .GET()
                .uri(uri)
                .build();
        return sendAsync(httpRequest, GeocodingResponse.class);
    }
```

Next, the `sendAsync` method needs to handle the decompression in  the `Content-Type` is set. I just quickly got this working so I'm not sure it this is the best way to handle it. 

```java
    private <T> CompletableFuture<T> sendAsync(HttpRequest httpRequest, Class<T> clazz) {
        return httpClient.sendAsync(httpRequest, HttpResponse.BodyHandlers.ofInputStream())
                .thenApply(resp -> {
                    try (InputStream rawStream = resp.body();
                         InputStream stream = "gzip".equals(resp.headers().firstValue("Content-Encoding").orElse(""))
                                 ? new GZIPInputStream(rawStream)
                                 : rawStream) {
                        String json = new String(stream.readAllBytes(), StandardCharsets.UTF_8);

                        if (resp.statusCode() != 200)
                            throw new GeocodioStatusCodeException(resp.statusCode(), json);

                        return gson.fromJson(json, clazz);
                    }
                    catch (IOException e) {
                        throw new IllegalStateException("Error reading response", e);
                    }
                });
    }
```

I was able to verify this works using `IntegrationTest`. 

My questions are:

- should the library allow the user to choose whether to request gzip responses or should it just always do it?
- is this a code acceptable?

**Comment by deansg** [comment]
I think we should allow the user whether to use GZip or not. However, it seems to me that this is a client-level property. I can't really imagine a scenario where a user will want to send some of the requests with gzip and others without. We can add constructor overloads that take a new "options" style argument which for now will only contain the "useGzip" property, or maybe it will contain the API key as well in the same class.
WDYT?

**Comment by ctmay4** [comment]
I completely agree this a client-level property. Having an option-style argument will be good and allow for expansion in the future.

On a side note, I was not properly closing the stream in my example above. This is better.

```java
    private <T> CompletableFuture<T> sendAsync(HttpRequest httpRequest, Class<T> clazz) {
        return httpClient.sendAsync(httpRequest, HttpResponse.BodyHandlers.ofInputStream())
                .thenApply(resp -> {
                    try (InputStream rawStream = resp.body();
                         InputStream stream = "gzip".equals(resp.headers().firstValue("Content-Encoding").orElse(""))
                                 ? new GZIPInputStream(rawStream)
                                 : rawStream) {
                        String json = new String(stream.readAllBytes(), StandardCharsets.UTF_8);

                        if (resp.statusCode() != 200)
                            throw new GeocodioStatusCodeException(resp.statusCode(), json);

                        return gson.fromJson(json, clazz);
                    }
                    catch (IOException e) {
                        throw new IllegalStateException("Error reading response", e);
                    }
                });
    }
```

**Comment by deansg** [comment]
Regarding your excerpt, I think we can simply extract a method that returns a single InputStream based on whether it's GZIPed or not, and then use it inside the try block. 

I'm also debating whether we want to use the logic you had to check if it's GZIPed or not or just count on the flag defined on the client without actually inspecting the response, which would be simpler.

Lastly, I'm not sure IllegalStateException is the most appropriate from its description. Maybe for now a simple RuntimeException will do.

Regarding the option-style argument, we should probably create another record (and use it with record-builder), and then add 2 new overloads to the constructor which receive it as an additional, last argument.

It's also important that we will add a CI-included unit test that uses a saved GZIPed response file in GIT.

I can probably get working on it in 2-3 days, or if you have the time you can submit a PR yourself.
Also, regardless, if you are currently using this library and is satisfied I would appreciate a star

@ctmay4

**Comment by ctmay4** [comment]
That all sounds fine, but one thing I'll point out.

> I'm also debating whether we want to use the logic you had to check if it's GZIPed or not or just count on the flag defined on the client without actually inspecting the response, which would be simpler.

When the client asks for the response to be zipped (`Accept-Encoding: gzip`) the web server does not have to. For example some servers will not compress responses that are below a certain size. So I think it is important to check the `Content-Encoding` returned in the response or you may try to decompress something that was not compressed.

> Also, in general, thank you for your contribution here, and if you are currently using this library and is satisfied I would appreciate a star

The star was already there!

**Comment by deansg** [comment]
@ctmay4 opened a PR, would appreciate your review
